<?php
    function translate() {
        $translate["Add a new post"]="Add a new post";
        $translate["Add a new user"]="Add a new user";
        $translate["Add post"]="Add post";
        $translate["Add user"]="Add user";
        $translate["ADMIN"]="ADMIN";
        $translate["Administrator"]="Administrator";
        $translate["Are you sure you want to delete the selected post? This process is irreversible."]="Are you sure you want to delete the selected post? This process is irreversible.";
        $translate["at"]="at";
        $translate["Author"]="Author";
        $translate["by"]="by";
        $translate["Change configuration"]="Change configuration";
        $translate["Choose post"]="Choose post";
        $translate["Choose user"]="Choose user";
        $translate["Content"]="Content";
        $translate["Date"]="Date";
        $translate["Delete post"]="Delete post";
        $translate["Edit blog configuration"]="Edit blog configuration";
        $translate["Edit post"]="Edit post";
        $translate["Go to admin panel"]="Go to admin panel";
        $translate["Hello"]="Hello";
        $translate["Language"]="Language";
        $translate["Last post to be shown in sidebar"]="Last post to be shown in sidebar";
        $translate["Latest posts"]="Latest posts";
        $translate["Login"]="Login";
        $translate["Logout"]="Logout";
        $translate["Manage posts"]="Manage posts";
        $translate["Moderator"]="Moderator";
        $translate["New pass"]="New pass";
        $translate["New user"]="New user";
        $translate["Nothing posted yet!"]="Nothing posted yet!";
        $translate["on"]="on";
        $translate["Pass again"]="Pass again";
        $translate["Pass"]="Pass";
        $translate["Password"]="Password";
        $translate["Passwords don't match."]="Passwords don't match.";
        $translate["Please select an option."]="Please select an option.";
        $translate["Posted"]="Posted";
        $translate["Remove user"]="Remove user";
        $translate["Repeat pass"]="Repeat pass";
        $translate["Show post"]="Show post";
        $translate["Showing posts by"]="Showing posts by";
        $translate["Start posting"]="Start posting";
        $translate["Submit"]="Submit";
        $translate["Time"]="Time";
        $translate["Title"]="Title";
        $translate["User already exists."]="User already exists.";
        $translate["User role"]="User role";
        $translate["Username"]="Username";
        $translate["Writer"]="Writer";
        $translate[""]="";
        $translate[""]="";
        $translate[""]="";
        $translate[""]="";
        $translate[""]="";
        $translate[""]="";
        $translate[""]="";
        $translate[""]="";
        $translate[""]="";
        $translate[""]="";
        
        return $translate;
    }
?>