<?php
    function translate() {
        $translate["Add a new post"]="Agregar publicación";
        $translate["Add a new user"]="Agregar un nuevo usuario";
        $translate["Add post"]="Publicar";
        $translate["Add user"]="Agregar usuario";
        $translate["ADMIN"]="ADMINISTRACIÓN";
        $translate["Administrator"]="Administrador";
        $translate["Are you sure you want to delete the selected post? This process is irreversible."]="E¿stá seguro que desea eliminar las publicaciones seleccionadas? Este proceso es irreversible.";
        $translate["at"]="a las";
        $translate["Author"]="Autor";
        $translate["by"]="por";
        $translate["Change configuration"]="Cambiar configuración";
        $translate["Choose post"]="Elija la publicación";
        $translate["Choose user"]="Elegir usuario";
        $translate["Content"]="Contenido";
        $translate["Date"]="Fecha";
        $translate["Delete post"]="Eliminar publicación";
        $translate["Edit blog configuration"]="Editar configuración del blog";
        $translate["Edit post"]="Editar publicación";
        $translate["Go to admin panel"]="Ir al panel de administración";
        $translate["Hello"]="Hola";
        $translate["Language"]="Idioma";
        $translate["Last post to be shown in sidebar"]="Cantidad de publicaciones a mostrar en barra lateral";
        $translate["Latest posts"]="Últimas publicaciones";
        $translate["Login"]="Iniciar sesión";
        $translate["Logout"]="Cerrar sesión";
        $translate["Manage posts"]="Administrar publicaciones";
        $translate["Moderator"]="Moderador";
        $translate["New pass"]="Nueva contraseña";
        $translate["New user"]="Nuevo usuario";
        $translate["Nothing posted yet!"]="¡Aún no hay publicaciones!";
        $translate["on"]="el";
        $translate["Pass again"]="Repetir contraseña";
        $translate["Pass"]="Contraseña";
        $translate["Password"]="Contraseña";
        $translate["Passwords don't match."]="Las contraseñas no coinciden";
        $translate["Please select an option."]="Por favor elija una opción.";
        $translate["Posted"]="Publicado";
        $translate["Remove user"]="Eliminar usuario";
        $translate["Repeat pass"]="Repetir contraseña";
        $translate["Show post"]="Información del post";
        $translate["Showing posts by"]="Mostrando publicaciones de";
        $translate["Start posting"]="Comienza a escribir";
        $translate["Submit"]="Enviar";
        $translate["Time"]="Hora";
        $translate["Title"]="Título";
        $translate["User already exists."]="El usuario ya existe.";
        $translate["User role"]="Rol del usuario";
        $translate["Username"]="Nombre de usuario";
        $translate["Writer"]="Escritor";
        $translate[""]="";
        $translate[""]="";
        $translate[""]="";
        $translate[""]="";
        $translate[""]="";
        $translate[""]="";
        $translate[""]="";
        $translate[""]="";
        $translate[""]="";
        $translate[""]="";
        
        return $translate;
    }
?>